### ISSUE TITLE
0.8 release missing from Maven Central

### ISSUE THREAD

**Issue by pniederw** [OracleLabs/Truffle#1]
Contrary to what the README suggests, 0.8 isn't available from Maven Central.

**Comment by chrisseaton** [comment]
Yes you're right - I'll look into it.

**Comment by pniederw** [comment]
Thanks! I meanwhile found 0.8 at http://lafo.ssw.uni-linz.ac.at/nexus/content/repositories/releases/, but Maven Central would be preferable.

**Comment by chrisseaton** [comment]
Yes the 0.8 release is there, as well as per-commit snapshots if you want to stay up to date. In JRuby we have a branch for release and a branch for the snapshots so we pick up any changes to the Truffle API early and can suggest any changes we need.

**Comment by eregon** [comment]
Truffle 0.8 is now available on Maven Central!
http://search.maven.org/#artifactdetails|com.oracle|truffle-api|0.8|jar
