### ISSUE TITLE
Maven snapshot repository is down

### ISSUE THREAD

**Issue by pniederw** [OracleLabs/Truffle#2]
Not sure what's the best place to report this, but http://lafo.ssw.uni-linz.ac.at is down. http://downforeveryoneorjustme.com/lafo.ssw.uni-linz.ac.at

**Comment by chrisseaton** [comment]
Yes, it is temporarily down - sorry about that. We are doing some maintenance and it should be up again soon. I'll post here when it is.

**Comment by pniederw** [comment]
Thanks! Any chance to get snapshots published to a well-known snapshot repository such as oss.sonatype.org (http://central.sonatype.org/pages/ossrh-guide.html)? That repository is mirrored by many parties around the world.

**Comment by chrisseaton** [comment]
I think it's up again. I'll look into Sonatype - we already do that for releases.
